[package]
name = "porter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "wrap_help", "unicode"] }
tokio = { version = "1.37.0", features = ["time", "rt-multi-thread", "full"] }
cidr = "0.2.2"